"use client";
import Image from "next/image";
import { useState } from "react";
import { ImageUp, LoaderCircle } from "lucide-react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/browser";

const allowed=["image/png","image/webp","image/jpeg"];
export function ProductUpload({productId,currentImageUrl}:{productId:string;currentImageUrl?:string|null}){const[progress,setProgress]=useState(0);const[preview,setPreview]=useState(currentImageUrl??null);async function upload(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!allowed.includes(file.type)){toast.error("Dozvoljeni su PNG, WebP i JPEG.");return;}if(file.size>5*1024*1024){toast.error("Slika može imati najviše 5 MB.");return;}setProgress(15);const extension=file.name.split(".").pop()?.toLowerCase()||"png";const path=`products/${productId}/${crypto.randomUUID()}.${extension}`;const supabase=createClient();setProgress(40);const{error}=await supabase.storage.from("product-images").upload(path,file,{contentType:file.type,upsert:false,cacheControl:"31536000"});if(error){toast.error(error.message);setProgress(0);return;}setProgress(80);const{data}=supabase.storage.from("product-images").getPublicUrl(path);const update=await supabase.from("products").update({image_url:data.publicUrl}).eq("id",productId);if(update.error){toast.error(update.error.message);setProgress(0);return;}setPreview(data.publicUrl);setProgress(100);toast.success("Slika proizvoda je postavljena.");location.reload();}return <div><span className="font-bold">Slika proizvoda</span><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-center"><div className="relative grid h-36 w-32 shrink-0 place-items-center overflow-hidden rounded-2xl border border-neutral-200 bg-neutral-50">{preview?<Image src={preview} alt="Trenutna slika proizvoda" fill sizes="128px" className="object-contain p-2"/>:<span className="px-3 text-center text-xs font-semibold text-neutral-400">Još nema postavljene slike</span>}</div><div className="min-w-0 flex-1"><label className="inline-flex min-h-12 w-full cursor-pointer items-center justify-center gap-2 rounded-full border border-neutral-300 px-5 font-bold transition active:scale-[.98] sm:w-auto"><input type="file" accept="image/png,image/webp,image/jpeg" className="sr-only" onChange={upload} disabled={progress>0&&progress<100}/>{progress>0&&progress<100?<LoaderCircle className="animate-spin" size={18}/>:<ImageUp size={18}/>}{preview?"Promeni sliku":"Postavi sliku"}</label>{progress>0?<div className="mt-2 h-2 overflow-hidden rounded-full bg-neutral-200"><div className="h-full bg-black transition-all" style={{width:`${progress}%`}}/></div>:null}<p className="mt-2 text-xs text-neutral-400">PNG, WebP ili JPEG, najviše 5 MB.</p></div></div></div>;}
